Pass along element through searchFn
HemantNegi/jquery.sumoselect pull request #309
Opened 2021-08-03 10:33 UTC by mbardelmeijer

Usecase for this: we can then use the element to look at the parent group, and show all elements that are found in the group above.

Group name
- Item 1
- Item 2
- Item 3

searchFn:

```
searchFn: function (haystack, needle, el) { // search function
     var elementContains = haystack.toLowerCase().indexOf(needle.toLowerCase()) !== -1;
     var groupContains = el.closest('.group').length ? el.parent().parent().find('label:first-child').html().toLowerCase().indexOf(needle.toLowerCase()) !== -1 : false;

     return !elementContains && !groupContains;
}
```

When searching for 'Group name', it will show all the 3 items, even tho the items don't have that search term.

Open for better implementations! Would be awesome to have optgroup search natively in sumoselect.

2021-08-03 12:49 UTC, Zenoo commented
Looks good to me.

Could you update the [README](https://github.com/HemantNegi/jquery.sumoselect/blob/master/README.md) and the [docs](https://github.com/HemantNegi/jquery.sumoselect/blob/6385b510827413d11459a316bcd8f2d04024eb7d/docs/index.html#L378) please?

2021-08-03 12:49 UTC, Zenoo requested changes
Looks good to me !

Could you update the [README](https://github.com/HemantNegi/jquery.sumoselect/blob/master/README.md) and the [docs](https://github.com/HemantNegi/jquery.sumoselect/blob/6385b510827413d11459a316bcd8f2d04024eb7d/docs/index.html#L378) please?

2021-08-04 07:09 UTC, mbardelmeijer commented
Done!

2021-08-04 07:43 UTC, Zenoo approved these changes

2021-08-04 07:45 UTC, merged